source 'http://rubygems.org'

gem 'rails', '2.3.7'
gem "surveyor", "0.19.2"
gem "rubyzip"
gem "nokogiri"
gem "daemons"
gem "erubis", ">= 2.6.5"
gem "ezprint"
gem "bluecloth"
gem "state_machine"
gem "memcache-client"
gem "wkhtmltopdf-binary"
gem "eventmachine"
gem "faye"

group :development do 
  gem "mailcatcher"
end

