source 'http://rubygems.org'

gem 'rails', '2.3.7'
gem "mailcatcher", :groups => [:development, :test]
gem "surveyor", "0.19.2"
gem "rubyzip"
gem "nokogiri"
gem "daemons"
gem "erubis", ">= 2.6.5"
gem "ezprint"
gem "bluecloth"
