#!/bin/bash
shopt -s lastpipe

scopes_file=".dev/scopes.txt"
test -r $scopes_file &&
  scopes="($(cat "$scopes_file" | sed '/^\(#.*\|\)$/d' | sed ':a;N;s/\n/|/g;ta'))"

grep -Eq "(fix|feat|docs|style|refactor|test|chore|rework|release)(\(${scopes:-.*}(/.+)?\))?: [a-z]" "$1"
result=$?
if test $result -ne 0
then echo "Please check the guidelines at http://karma-runner.github.io/latest/dev/git-commit-msg.html$(test -n "$scopes" && echo ", the scope should be one of $scopes as defined in $scopes_file")"
fi
exit $result
