#!/bin/bash
# shopt -s lastpipe

scopes_file=".dev/scopes.txt"
test -r "$scopes_file" &&
  scopes="($(grep -vE '^\s*(#|$)' "$scopes_file" | paste -sd '|' - ))"

head -1 "$1" | grep -Eq "^(fix|feat|enhance|docs|style|refactor|test|build|rework|release|revert)(\(${scopes:-.*}(/.+)?\))?: [A-Za-z]"
result=$?
if test $result -ne 0
then printf "Invalid commit message: '$(head -1 "$1")'
Please check the guidelines at http://karma-runner.github.io/6.2/dev/git-commit-msg.html$(test -n "$scopes" && echo " with the scope one of $scopes as defined in $scopes_file")" >&2
fi
exit $result
